[package]
name = "stream_zipper"
version = "0.2.0"
authors = ["Pyry Kontio <pyry.kontio@drasa.eu>"]
description = "A crate for stream decompressing zip files."
license = "MIT"
exclude = [
    "tests/assets/*",
]

[dependencies]
nom = "5.0.1"
miniz_oxide = "0.3.6"
